name: Production CD

on:
  pull_request:
    types: [closed]
    branches: [production]

jobs:
  build:
    runs-on: production-cd
    steps:
      - uses: actions/checkout@v3
      - name: Remove files
        run:
          rm README.md
          rm **/**.test.ts*
